image: garland/aws-cli-docker

variables:
  AWS_DEFAULT_REGION: us-east-2
  AWS_ACCESS_KEY_ID: AKIAJLFOAUGAHNAKXN7A

test:
  script:
    - aws cloudformation validate-template --template-body file://mail.yaml