---
Description: A mail server setup
Resources:
  MailServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default:
          - install_cfn
          - utilities
          - postfix
          - spamassassin
          - dns

        install_cfn:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=1
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.MailServer.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --configsets default --resource MailServer --stack ${AWS::StackName} --region ${AWS::Region}
                runas=root

          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                - /etc/cfn/cfn-hup.conf
                - /etc/cfn/hooks.d/cfn-auto-reloader.conf


        utilities:
          files:
            /home/ubuntu/.aws/config:
              content: |
                [default]
                region = us-east-2
            /root/.aws/config:
              content: |
                [default]
                region = us-east-2
            /etc/hostname:
              content: mx1.dyksen.net
          packages:
            apt:
              zsh: []
              telnet: []
              htop: []
              jq: []
          commands:
            01_hostname:
              command: hostname mx1.dyksen.net
            02_zprezto:
              command: sudo -u ubuntu git clone --recursive git://github.com/ejdyksen/prezto.git /home/ubuntu/.zprezto
              test: "! [ -d /home/ubuntu/.zprezto ]"
            03_dotfiles:
              command: sudo -u ubuntu git clone git://github.com/ejdyksen/dotfiles.git /home/ubuntu/.dotfiles
              test: "! [ -d /home/ubuntu/.dotfiles ]"
            04_dotfiles_install:
              command: sudo -u ubuntu bash /home/ubuntu/.dotfiles/install.sh
            05_chsh:
              command: chsh -s /usr/bin/zsh ubuntu


        postfix:
          packages:
            apt:
              postfix: []
          files:
            /etc/postfix/transport:
              content: |
                dyksen.net          smtp:mail.dyksen.net:26
                downstairslabs.com  smtp:mail.dyksen.net:26
          commands:
            01_postfix_main:
              command: postconf -e "myhostname = mx1.dyksen.net" "myorigin = \$mydomain" "inet_interfaces = all" "mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128" "relay_domains = dyksen.net, downstairslabs.com" "relayhost = mail.dyksen.net:26"
            02_postmap:
              command: postmap /etc/postfix/transport
            03_reload:
              command: postfix reload
          services:
            sysvinit:
              postfix:
                enabled: true
                ensureRunning: true


        spamassassin:
          packages:
            apt:
              spamassassin: []
              pyzor: []
              razor: []
          files:
            /usr/local/bin/spamfilter.sh:
              mode: '000755'
              content: |
                #!/usr/bin/env bash

                SENDMAIL=/usr/sbin/sendmail
                SPAMASSASSIN=/usr/bin/spamc

                logger <<<"Spam filter piping to SpamAssassin, then to: $SENDMAIL $@"
                ${SPAMASSASSIN} | ${SENDMAIL} "$@"

                exit $?
            /etc/spamassassin/local.cf:
              mode: '000644'
              content: |
                # This is the right place to customize your installation of SpamAssassin.
                #
                # See 'perldoc Mail::SpamAssassin::Conf' for details of what can be
                # tweaked.
                #
                # Only a small subset of options are listed below
                #
                ###########################################################################

                use_bayes 1
                required_score 3.0

                bayes_auto_learn 1

                bayes_auto_learn_threshold_spam         8.0
                bayes_auto_learn_threshold_nonspam      -1.0

                bayes_path /var/spamassassin/bayes_db/bayes
                bayes_file_mode 0777

                dns_server 127.0.0.1
            /etc/cron.hourly/backup-spamassassin:
              mode: '000755'
              content: |
                #!/usr/bin/env bash
                cd /tmp
                now=`date -u +%FT%T`Z
                filename=sa-learn-backup-$now.txt
                sa-learn --backup > $filename
                backup_size=`du -k "$filename" | cut -f1`
                if [ $backup_size -gt 2000 ]
                then
                  aws s3 cp $filename s3://ejdyksen-spam/sa-backup/$filename --storage-class STANDARD_IA
                fi
                rm -f $filename
            /usr/local/bin/restore-spamassassin:
              mode: '000755'
              content: |
                #!/usr/bin/env bash
                object=s3://ejdyksen-spam/`aws s3api list-objects-v2 --bucket ejdyksen-spam --prefix 'sa-backup/' | jq -r '.Contents | max_by(.Key) | .Key'`
                aws s3 cp $object restore.txt
                sudo -u debian-spamd sa-learn --restore restore.txt
                rm -f restore.txt
          commands:
            01_create_bayes_db:
              command: mkdir /var/spamassassin && chown debian-spamd /var/spamassassin && chgrp debian-spamd /var/spamassassin && chmod 777 /var/spamassassin
            02_restore_from_backup:
              command: /usr/local/bin/restore-spamassassin
              cwd: /tmp
            03_setup_content_filter:
              command: postconf -P "smtp/inet/content_filter=spamf"
            04_setup_spamfilter_transport:
              command: echo -n "spamf     unix  -       n       n       -       -       pipe\n  user=debian-spamd argv=/usr/bin/spamc -f -e /usr/sbin/sendmail -oi -f \${sender} \${recipient}" >> /etc/postfix/master.cf
            05_enable_spamassassin:
              command: sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/spamassassin
            06_enable_spamassassin_cron:
              command: sed -i 's/CRON=0/CRON=1/g' /etc/default/spamassassin
            07_reload_postfix:
              command: postfix reload
          services:
            sysvinit:
              spamassassin:
                enabled: true
                ensureRunning: true


        dns:
          packages:
            apt:
              bind9: []
              bind9utils: []
          services:
            sysvinit:
              bind9:
                enabled: true
                ensureRunning: true


    Properties:
      ImageId: ami-d1cb91b4
      InstanceType: t2.nano
      AvailabilityZone: us-east-2a
      SecurityGroups:
      - !Ref MailSecurityGroup
      IamInstanceProfile: !Ref MailServerInstanceProfile
      KeyName: ejd
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          apt-get update
          apt-get -y install python-pip
          pip install --upgrade pip
          pip install awscli
          pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
          cp /usr/local/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
          chmod +x /etc/init.d/cfn-hup
          update-rc.d cfn-hup defaults
          service cfn-hup start

          /usr/local/bin/cfn-init -v --configsets default --resource MailServer --stack ${AWS::StackName} --region ${AWS::Region}

          /usr/local/bin/cfn-signal --exit-code $? --resource MailServer --stack ${AWS::StackName} --resource MailServer --region ${AWS::Region}

          apt-get -y upgrade
          apt-get -y dist-upgrade
          reboot

    CreationPolicy:
      ResourceSignal:
        Timeout: PT30M

  VpcIPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref MailServer
      AllocationId: 'eipalloc-c5d11cac'

  MailServerInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: '/'
      Roles:
        - !Ref MailServerRole

  MailServerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: '/'
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:*"
                Resource:
                  - "arn:aws:s3:::ejdyksen-spam"
                  - "arn:aws:s3:::ejdyksen-spam/*"

  MailSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 68.48.162.3/32
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 35.10.2.33/32
      - IpProtocol: tcp
        FromPort: '25'
        ToPort: '25'
        CidrIp: 0.0.0.0/0
