---
Description: A mail server setup
Resources:
  MailServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default:
          - install_cfn
          - utilities
          - postfix
          - spamassassin
          - dns

        install_cfn:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=1
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.MailServer.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --configsets default --resource MailServer --stack ${AWS::StackName} --region ${AWS::Region}
                runas=root

          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                - /etc/cfn/cfn-hup.conf
                - /etc/cfn/hooks.d/cfn-auto-reloader.conf

        utilities:
          files:
            /home/ec2-user/.aws/config:
              content: |
                [default]
                region = us-east-2
            /root/.aws/config:
              content: |
                [default]
                region = us-east-2
          packages:
            yum:
              telnet: []
              htop: []
              jq: []

        postfix:
          packages:
            yum:
              postfix: []
          files:
            /etc/postfix/transport:
              content: |
                dyksen.net          smtp:mail.dyksen.net:26
                downstairslabs.com  smtp:mail.dyksen.net:26

          commands:
            01_remove_sendmail:
              command: yum remove -y sendmail && alternatives --set mta /usr/sbin/sendmail.postfix
            02_postfix_main:
              command: postconf -e "myhostname = mx1.dyksen.net" "myorigin = \$mydomain" "inet_interfaces = all" "mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128" "relay_domains = dyksen.net, downstairslabs.com" "relayhost = mail.dyksen.net:26"
            03_postfix_master:
              command: sudo postconf -P "smtp/inet/content_filter=spamassassin"
            04_postmap:
              command: postmap /etc/postfix/transport

          services:
            sysvinit:
              postfix:
                enabled: true
                ensureRunning: true

        spamassassin:
          packages:
            yum:
              spamassassin: []
          files:
            /etc/cron.daily/backup-spamassassin:
              mode: '000755'
              content: |
                #!/usr/bin/env bash
                cd /tmp
                now=`date -u +%FT%T`Z
                filename=sa-learn-backup-$now.txt
                sa-learn --backup > $filename
                backup_size=`du -k "$filename" | cut -f1`
                if [ $backup_size -gt 2000 ]
                then
                  aws s3 cp $filename s3://ejdyksen-spam/sa-backup/$filename --storage-class STANDARD_IA
                fi
                rm -f $filename
            /usr/local/bin/restore-spamassassin:
              mode: '000755'
              content: |
                #!/usr/bin/env bash
                object=s3://ejdyksen-spam/`aws s3api list-objects-v2 --bucket ejdyksen-spam --prefix 'sa-backup/' | jq -r '.Contents | max_by(.Key) | .Key'`
                aws s3 cp $object restore.txt
                sa-learn --restore restore.txt
                rm -f restore.txt

          commands:
            restore_from_backup:
              cwd: /tmp
              command: /usr/local/bin/restore-spamassassin

          services:
            sysvinit:
              spamassassin:
                enabled: true
                ensureRunning: true


        dns:
          packages:
            yum:
              bind: []
              bind-utils: []
          services:
            sysvinit:
              named:
                enabled: true
                ensureRunning: true


    Properties:
      ImageId: ami-58277d3d
      InstanceType: m4.large
      SecurityGroups:
      - !Ref MailSecurityGroup
      IamInstanceProfile: !Ref MailServerInstanceProfile
      KeyName: ejd
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          yum update -y

          /opt/aws/bin/cfn-init -v --configsets default --resource MailServer --stack ${AWS::StackName} --region ${AWS::Region}

          /opt/aws/bin/cfn-signal --exit-code $? --resource MailServer --stack ${AWS::StackName} --resource MailServer --region ${AWS::Region}

    CreationPolicy:
      ResourceSignal:
        Timeout: PT30M

  VpcIPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref MailServer
      AllocationId: 'eipalloc-c5d11cac'

  MailServerInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: '/'
      Roles:
        - !Ref MailServerRole

  MailServerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: '/'
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:*"
                Resource:
                  - "arn:aws:s3:::ejdyksen-spam"
                  - "arn:aws:s3:::ejdyksen-spam/*"

  MailSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '25'
        ToPort: '25'
        CidrIp: 0.0.0.0/0
